### ISSUE TITLE
global_lib.py:214: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by ozgurgul** [the4thdoctor/pg_chameleon#107]
Hi Federico, 
**Describe the bug**
When I run the  `chameleon show_status --config default`
It throws a warning about YAML loading.. 

_**/usr/bin/venv/lib64/python3.6/site-packages/pg_chameleon/lib/global_lib.py:214: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
**_

**To Reproduce**
When you run [` chameleon show_status --config default`] command 
to see the status of replication

**Expected behavior**
No warning message.
**Screenshots**
![Screenshot_YAMLDeprecatedWarning](https://user-images.githubusercontent.com/10107881/74343244-aa92a780-4da2-11ea-9ec8-ad6ec911ecd5.png)

**Environment(please complete the following information):**
 - OS: [CentOS Linux release 7.7.1908]
 - MySQL Version[10.4.11]
 - PostgreSQL Version[PostgreSQL 12.1 (Debian 12.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by g
cc (Debian 8.3.0-6) 8.3.0, 64-bit ]
 - Python Version [Python 3.6.8]
 - Cloud hosted database [ PostgreSQL on Docker Container and MySQL on Docker Container] 

**Additional context**

**Comment by the4thdoctor** [comment]
Hi, sorry for the delay. I've fixed the issue in the version v2.0.11.
Can you pleae update to the latest version and try again? 
If warning still appears I'll have a look for what is causing it.
Many thanks

**Comment by ozgurgul** [comment]
Thanks so much Federico. I'll take a look at it this week.

**Comment by the4thdoctor** [comment]
I assume the problem is solved.
