### ISSUE TITLE
is this normal: i_skipped > 0 on a finished batch

### ISSUE THREAD

**Issue by martinsperl-kognitiv** [the4thdoctor/pg_chameleon#11]
I have been looking at some of the tables used by pg_chameleon and one thing that is interresting is the fact that in t_replica_batch the i_skipped column is not 0 for a finished batch.

Is this normal behaviour?

i_id_batch|b_replayed|i_replayed|i_skipped
--|--|--|--
9|t|40664|10
10|t|4123|2399
11|t|7465|9
12|t|39083|23
13|t|2571|3
14|t|23766|9
15|t|24464|8
16|t|1747|7
17|f|50000|\N
18|f|\N|\N

Just wanting to make sure...

**Comment by the4thdoctor** [comment]
Mmm looks like you have some tables without the primary key. In that case the row images are pulled but skipped by the Replay procedure

**Comment by martinsperl-kognitiv** [comment]
do we need to change that - would we have dataloss during the migration?
This does not show up in the postgres logs either - the function contains lots of RAISE DEBUG, but nothing else, so I can not easily identify the tables...

**Comment by the4thdoctor** [comment]
Yes, unfortunately the primary key is required for the replica.
You can check the tables registered in t_replica_tables against your schema.
Only the tables with the primary key are stored in the replica catalog.

**Comment by martinsperl-kognitiv** [comment]
maybe add a warning about those that are not added?

**Comment by the4thdoctor** [comment]
sure, I can add a warning.

**Comment by martinsperl-kognitiv** [comment]
As a note: these " errors" do not show up in the t_discarded_rows table either!

**Comment by the4thdoctor** [comment]
they are no errors at all. the rows are just pulled but not replayed

**Comment by martinsperl-kognitiv** [comment]
so these are discarded - so imo they should show up in the discarded table...

**Comment by martinsperl-kognitiv** [comment]
thanks for the clarification

**Comment by the4thdoctor** [comment]
the discarded table is for the rows with rubbish data.

**Comment by the4thdoctor** [comment]
added a warning in branch VER1.5

**Comment by martinsperl-kognitiv** [comment]
thanks!

**Comment by martinsperl-kognitiv** [comment]
Maybe change fn_process_batch:
```
...
	DELETE FROM sch_chameleon.t_log_replica
    		    WHERE
    			    i_id_batch=v_i_id_batch
    		    ;
				
		GET DIAGNOSTICS v_i_skipped = ROW_COUNT;
...
```
into something similar to this:
```
	INSERT INTO sch_chameleon.t_discarded_rows SELECT * from sch_chameleon.t_log_replica
    		    WHERE
    			    i_id_batch=v_i_id_batch
    		    ;
         DELETE FROM sch_chameleon.t_log_replica
    		    WHERE
    			    i_id_batch=v_i_id_batch
    		    ;
				
		GET DIAGNOSTICS v_i_skipped = ROW_COUNT;
```
(I know that the tables are not identical, so it may not work in an identical fashion but may need to get modified - maybe a separate table for those?)

**Comment by the4thdoctor** [comment]
I need to think about that. this approach will surely lead to  bloating of the table with the skipped rows.
The amount of data coming from the replica can be very large.
