### ISSUE TITLE
Migrating MySQL utf8mb4 column

### ISSUE THREAD

**Issue by irogers** [the4thdoctor/pg_chameleon#110]
Hello,

Firstly, thanks for the great tool.

I am coming up against an error with migrating a utf8mb4 encoded column. On initiating the replication I get the following result.

Source
``` sql
SELECT  HEX(column) 
FROM table;
```
Gives `F09F9095`

Destination
``` sql
SELECT encode(column::bytea, 'hex') 
FROM table;
```
Gives `3f` where I would expect  `F09F9095`

Is migration of utf8mb4 columns supported?

Thanks

**Environment:**
 - OS: Ubuntu 18.04
 - MySQL Version 5.7.22
 - PostgreSQL Version 11.7
 - Python Version 3.6
 - Cloud hosted database PostgreSQL on DigitalOcean

**Comment by the4thdoctor** [comment]
I never tested the columns utf8mb4, but I can give it a try to have it supported.
Can you please provide an example for the CREATE TABLE so I can experiment on a well known setup?
Thanks.

**Comment by the4thdoctor** [comment]
Hi, the column bytea is already hex encoded.

I've tested with a single pixel jpg with the table defined this way. 

```
CREATE TABLE `testbin` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bindata` blob DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```
I've uploaded a binary file in the field bindata and the values in MySQL and PostgreSQL coincide.

The queries I've run on MySQL and PostgreSQL:

MySQL
```
SELECT
	md5(HEX(bindata))
FROM 
	testbin;
8f9bb371180b80abb07259ee9a3a6bfc
```

PostgreSQL

```
SELECT 
	md5(bindata) 
FROM 
	sch_sakila.testbin
8f9bb371180b80abb07259ee9a3a6bfc
;
```

Please note that when the row is updated from the replica stream the letters are changed in lowercase.
