### ISSUE TITLE
Pip installs unsupported PyMySQL 0.10.0

### ISSUE THREAD

**Issue by JellyWX** [the4thdoctor/pg_chameleon#117]
**Describe the bug**
Using PyMySQL 0.10.0 (which is as installed by PyPI), an exception is raised immediately when running

**To Reproduce**
* Open a fresh venv and install with `pip install pg_chameleon`
* Type `chameleon` or `python -m pg_chameleon`
* An exception is raised: `ImportError: cannot import name 'charset_to_encoding'`

**Expected behavior**
No exception should appear. Program should run with the requirements as installed

**Environment(please complete the following information):**
 - OS: Linux Mint 20
 - MySQL: 8 but not necessary
 - PostgreSQL: 12 but not necessary
 - Python: 3.6.11 and 3.8.2

**Additional context**
PyMySQL 0.9.3 works fine. Requirements just need changing so that 0.9.3 is installed instead of 0.10.0 when this package is installed

**Comment by JellyWX** [comment]
Reading the `setup.py`, it seems that this should be occuring. Potentially this is a bug with pip or something else

**Comment by the4thdoctor** [comment]
I'm about to release the version 2.0.14 which specifies that PyMySQL should be the version < 0.10.0.
The [PR 326 on mysql-replication](https://github.com/noplay/python-mysql-replication/pull/326) should fix the problem.

**Comment by the4thdoctor** [comment]
Fixed with the last release.
