### ISSUE TITLE
Question: how to replicate 2 schema from the same mysql-instance to a single postgres-database (different schema)

### ISSUE THREAD

**Issue by martinsperl-kognitiv** [the4thdoctor/pg_chameleon#12]
Is it possible to run a replication of 2 mysql schema on the same mysql instance (thus sharing the same binlogs) to a single postgress database instance but to different schema.

I am not sure if there would be a problem with the shared sch_chameleon schema that is used as the intermediate. Also I see that possibly the same binlogs may get processed twice.

Thanks, Martin

**Comment by martinsperl-kognitiv** [comment]
For clarification here the  show databases from the mysql side:
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| pg_chameleon       |
| switchv2           |
| tableau            |
+--------------------+
```

Switchv2 and tableau should get moved to the same database  in postgres with the schema names switchv2 and tableau respectively.

**Comment by the4thdoctor** [comment]
Hi, you can create a configuration file per each schema you want to replicate.

For example, if you want to replicate the tableau database into the tableau schema copy the default.yaml file into a new file named tableau.yaml.

Edit the file tableau.yaml and change the configuration parameters

my_database:  tableau
my_server_id: 101
dest_schema: 'tableau'
source_name: 'tableau'

Then run 
`chameleon.py add_source --config tableau`
`chameleon.py init_replica --config tableau`
`chameleon.py start_replica --config tableau`

Do the same for switchv2 ensuring the values of server_id and source_name are different from default.yaml and tableau.yaml.

**Comment by the4thdoctor** [comment]
To display the replica status and the sources registered you can run 
`chameleon.py show_status --config default`

**Comment by martinsperl-kognitiv** [comment]
I thought because both would use the same table that they would corrupt each other
I assume that this means: yes we can handle such situations.
