### ISSUE TITLE
Lock free table initialisation

### ISSUE THREAD

**Issue by rascalDan** [the4thdoctor/pg_chameleon#121]
We have a large source MySQL (MariaDB 10.3 to be more precise) database that we can't really take out of action. The problem that we have then, is that the initial copy of data from the MySQL source to PostgreSQL requires a lock on the source table throughout the whole process. (FLUSH TABLE .. WITH READ LOCK is the statement I think taking this lock)

I understand why it's done this way (master coordinates I think), but I did wonder if it would instead be possible to perform the initial copy within a repeatable read transaction instead. I'm thinking maybe something like:
* Acquire table lock
* Begin transaction
* Read master coordinates
* Release lock
* Copy data
* End transaction

This should mean the table content will be consistent with the master coordinates when the transaction is started and thus the copy should be able to run without needing the table to be locked.

Failing that... I'd love a way to setup a replica some other without locking the source tables (210M records / 23GB is the biggest and the locked time would be prohibitive)

**Comment by the4thdoctor** [comment]
merged PR #122
