### ISSUE TITLE
init_replica fails if source has tinyint(1) with a value > 1

### ISSUE THREAD

**Issue by pyrite357** [the4thdoctor/pg_chameleon#126]
**Describe the bug**
init_replica fails when source MySQL database has a value of 2 in a tinyint(1) column. Works in 2.0.14, but the process bombs and quits to the terminal in 2.0.15 with SQL errors in the MainProcess.

This happens when the config file has:

type_override:
  "tinyint(1)":
    override_to: boolean
    override_tables:
      - "*"

**To Reproduce**
Fails in 2.0.15, but works in 2.0.14

**Expected behavior**
Expect init_replica to finish even if the source database is poorly normalized

**Screenshots**
No screenshots available, would be nice if there was an error log

**Environment(please complete the following information):**
 - OS: CentOS Linux release 8.2.2004 (Core)
 - MySQL 5.7.16
 - PostgreSQL 12.4 
 - Python Version 3.6.8
 - Vagrant VM

**Additional context**

**Comment by the4thdoctor** [comment]
I think I've found the culprit. pushed to the branch v2.0. Can you test it please?

**Comment by the4thdoctor** [comment]
fixed in with release 2.0.16

**Comment by pyrite357** [comment]
Sorry I didn't have time to test @the4thdoctor , no doubt I'll be testing the 2.0.16 release though. I'll let you know if I run into any problems again like this. Thank you so much!
