### ISSUE TITLE
Unable to create the venv virtual environment

### ISSUE THREAD

**Issue by keithchristian** [the4thdoctor/pg_chameleon#134]
$ sudo python3 -m venv venv
Error: Command '['/xxx/xxx/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
[

**Comment by keithchristian** [comment]
Any idea about this error?

**Comment by vachigaggl** [comment]
This has nothing to do with pg_chameleon. You need to install the correct version of pip and venv for your python environment for this to work. 
Please apt-get (assuming that you are running Ubuntu) the python-3.X-venv that corresponds to your python-3.X installation and close this issue.

See also kosmičák answer here: https://askubuntu.com/questions/1285650/cannot-install-python-venv-on-ubuntu-20-04-after-upgrading-from-bionic
