### ISSUE TITLE
Replication not working on 

### ISSUE THREAD

**Issue by igomez-arbiquity** [the4thdoctor/pg_chameleon#145]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - OS: [e.g. Devuan GNU/Linux]
 - MySQL Version[e.g. 5.7.27]
 - PostgreSQL Version[e.g. 11]
 - Python Version [e.g. 3.5]
 - Cloud hosted database [e.g PostgreSQL on AWS RDS and MySQL on Google Cloud] 

**Additional context**

**Comment by the4thdoctor** [comment]
empty version of #146. closing it
