### ISSUE TITLE
Consider updating mysql-replication to 0.30

### ISSUE THREAD

**Issue by amq** [the4thdoctor/pg_chameleon#149]
**Is your feature request related to a problem? Please describe.**

mysql-replication fixed long json and null json handling. This should fix a common problem:

```
  File "/home/python/.local/lib/python3.9/site-packages/pymysqlreplication/packet.py", line 414, in read_binary_json_object
    raise ValueError('Json length is larger than packet length')
```

**Describe the solution you'd like**

Update mysql-replication. Hopefully, the 0.26 problem with utf8mb4 is fixed by now.

**Describe alternatives you've considered**

**Additional context**

**Comment by the4thdoctor** [comment]
Unfortunately I can't update yet as there is a critical bug on the DDL replica.
https://github.com/julien-duponchelle/python-mysql-replication/issues/380

I've reported the issue in June but it's still unresolved. 
Until then I won't be able to upgrade the library.

**Comment by the4thdoctor** [comment]
The bug fix for the library is now out and I'll soon make a new release using the 0.31 library.

**Comment by the4thdoctor** [comment]
We are good to go for using the library 0.31, I'll try to make a new release ASAP

**Comment by the4thdoctor** [comment]
Version 2.0.19 is out.
