### ISSUE TITLE
pg_chameleon read lag with no errors

### ISSUE THREAD

**Issue by firdoze1234** [the4thdoctor/pg_chameleon#150]
Hello I am using pg_chameleon to replicate a postgres database (Version 14.5 on RHEL 8.6) from MySQL (Version 5.7.39-42-log Percona Server on RHEL 7.9)

The set up was fine and the replica initialized with no issues, but as soon as I start the replica it starts lagging almost immediately and the lag refreshes every hour with no changes to data on the postgres side.

The migration_mysql_replay.log is empty and every hour this gets captured in the migration_mysql_read.log:
2022-11-17 06:05:55 read_replica INFO: Saved master data for source: mysql
2022-11-17 07:05:45 read_replica INFO: Saved master data for source: mysql
2022-11-17 08:05:49 read_replica INFO: Saved master data for source: mysql

Any idea what could be wrong here?

**Comment by the4thdoctor** [comment]
can you post your complete setup please?
please obfuscate any sensible data or password.
thanks.
