### ISSUE TITLE
only UPDATE event not applied on PostgreSQL

### ISSUE THREAD

**Issue by giant-ksj** [the4thdoctor/pg_chameleon#158]
**Describe the bug**

After 'chameleon start_replica' everything is ok.  show_status tells status = running and consistent = yes.
Every Logs also fine (in ~/.pg_chameleon/logs and $PGDATA/log)
but few data is not same with MySQL data.  When i checked pg_stat_user_tables, All table's n_tup_upd is 0.

So, I find some information on kafka configuration. ([Link](https://debezium.io/documentation/reference/stable/connectors/mysql.html))

"Check binlog_row_value_options variable, and make sure that value is not set to PARTIAL_JSON, since in such case connector might fail to consume UPDATE events."

Unfortunately, my env binlog_row_value_options is 'PARTIAL_JSON'.  Is that a right guid for this problem?

**To Reproduce**

**Expected behavior**

**Screenshots**

## PostgreSQL stat - 0 Update row.
![image](https://user-images.githubusercontent.com/130650337/233648138-377d2304-0345-4b67-afef-bf2efb1ec9d2.png)

## MySQL stat - Update event occur.
![image](https://user-images.githubusercontent.com/130650337/233648560-c45e82f9-3937-4e68-a450-81b1f89ab084.png)

**Environment(please complete the following information):**
 - OS: [e.g. Devuan GNU/Linux]
 - MySQL Version[e.g. 5.7.27]
 - PostgreSQL Version[e.g. 11]
 - Python Version [e.g. 3.5]
 - Cloud hosted database [e.g PostgreSQL on AWS RDS and MySQL on Google Cloud] 

**Additional context**

**Comment by the4thdoctor** [comment]
the values in pg_stat_user_tables is just an estimation and definitely not good to determine whether the rows are being replicated or not.

**Comment by giant-ksj** [comment]
@the4thdoctor 
When pg_chameleon init & start replica from 'MySQL Slave' then must disable 'binlog_row_value_options' parameter on MySQL DB.  If not, only 'update' event not replicate to PostgreSQL.
