### ISSUE TITLE
SQLCODE: 22008 SQLERROR: ERROR:  date/time field value out of range: "0000-00-00 00:00:00"

### ISSUE THREAD

**Issue by ghost** [the4thdoctor/pg_chameleon#16]
Is there a way to "transform" those?
```
Jul 24 13:55:39: [ERROR] - pg_lib.py (510): b'INSERT INTO "cpc"."meta_config" ("id","key","value","created_at","updated_at") VALUES (\'1\',\'payment_overdue_limit\',\'30\',\'0000-00-00 00:00:00\',\'0000-00-00 00:00:00\');'
```

I understand that it should look like this:
```
insert into subscriptions_sub(datetime_created) values (NULLIF(your_field_name,'0000-00-00 00:00:00')::timestamp)
```
to be totally safe...

**Comment by the4thdoctor** [comment]
The row image doesn't carry informations about the data type. Maybe querying the postgres system catalogue when the procedure starts the replay can fix this sort of issues. I'm adding this enhanchement tentatively to the version 1.7 (currently working on the 1.6) as this require time to be correctly addressed.

**Comment by the4thdoctor** [comment]
I've wrongly addressed the issue 22 in the last commit. However the fix for this issue will appear in the upcoming version 1.7
