### ISSUE TITLE
MySQL changes not reflected in Postgres

### ISSUE THREAD

**Issue by samplesizeofone** [the4thdoctor/pg_chameleon#2]
Hi,

I'm test driving pg_chameleon, but I've hit a snag. None of the changes in MySQL show up in Postgres (both tables and rows). I've put all the relevant information I can think of into https://gist.github.com/samplesizeofone/bf9019e8ff0dcb272405afa3c47c7d09 (pg_chameleon config, the relevant lines from my deploy, logged output, test sql, and some of sch_chameleon.*).

It looks like information is making it to sch_chameleon.t_log_replica. I'm logged in as vagrant, which should be the replica user.

Any help is very appreciated.

Thanks!

**Comment by the4thdoctor** [comment]
Hi, thanks for the report. I'll have a look this week and when back from holiday. 
In the meanwhile can you please give me this query output after the init replica? 
Select * from sch_chameleon.t_replica_tables? 
Thanks for the feedback

**Comment by samplesizeofone** [comment]
Hi, I'm afraid my lack of postgres experience is showing. I was setting the schema to 'spaeth' and conflating that with the database 'spaeth'. My boss took a look and was able to see the replication happening, so it's all good.

Thanks for getting back to me, though. I appreciate it.

All the best.

**Comment by the4thdoctor** [comment]
I tested the configuration you posted on gist on my virtual machine (virtualbox I have no experience with vagrant unfortunately) and it worked fine. 
Thanks for the report. I hope the software will be useful :-)
I'm closing the issue. 
Kind regards
