### ISSUE TITLE
Handling of datatypes when migrating schema

### ISSUE THREAD

**Issue by agseekda** [the4thdoctor/pg_chameleon#21]
Hi,

We are currently evaluating pg_chameleon for migrating our database from mysql to postgresql with minimal downtime.

One blocking issue we found is that in mysql booleans are represented as tinyint(1) or bit(1) while in postgresql our ORM mapper expects real booleans.

We didn't find a way to do this kind of transformation with pg_chameleon. Other tools like pgloader have this built in.

Question is can this functionality be added?

**Comment by the4thdoctor** [comment]
Hi, currently I have no flexibility in type handling.  I need to check if is possible to have it implemented in the version 1 or if I have to bump it to the version 2 (probably out by the end of the year.

**Comment by the4thdoctor** [comment]
the override is possible, however the risk of breaking the replica is very concrete.
for example if you insert a value larger that 1 in a tinyint(1) the boolean on postgres will cause an error.
I need to investigate a solid way to make it work so adding this feature to the version 1.7 at least.

**Comment by the4thdoctor** [comment]
@agseekda you can test the functionality on the branch [type_override](https://github.com/the4thdoctor/pg_chameleon/tree/type_override). The configuration file requires a mapping for the type override. the configuration-example.yaml have the example override for tinyint(1).
The override_to key specifies the type to override. This must be a postgresql type.
The override_tables allow to specify which tables will get the override. Leave the star if you want to apply the override to all the tables.
Currently the override works only at create time. 
Please let me know if it works for you.
Thanks
