### ISSUE TITLE
[ERROR] - global_lib.py (416): An error occurred during the replica.

### ISSUE THREAD

**Issue by love0906** [the4thdoctor/pg_chameleon#22]
At the MySQL：

alter table kp_web_log add key idx_idx_mobile(idx_mobile)

[ERROR] - global_lib.py (416): An error occurred during the replica. (<class 'KeyError'>, KeyError('idx_mobile',), <traceback object at 0x7fbf3eced448>)

**Comment by the4thdoctor** [comment]
Thanks, I'll have a look to the regexp.

**Comment by the4thdoctor** [comment]
the fix will come out in the upcoming version v1.6

**Comment by love0906** [comment]
Thanks
