### ISSUE TITLE
pg Schema name upper case is dropped to lowercase in init_replica.

### ISSUE THREAD

**Issue by lifeboy** [the4thdoctor/pg_chameleon#32]
Using a schema name like "CamelCaseSchema" in the configfile.yaml, creates a schema "camelcaseschema".  When the replication is actually run though, the script again looks for "CamelCaseSchema", which it then doens't find and an error is generated.

**Comment by the4thdoctor** [comment]
fixed in commit [28be9a](https://github.com/the4thdoctor/pg_chameleon/commit/57556783f49d1fa6b554f548310935a5c328be9a)
