### ISSUE TITLE
Update statement can not be applied immediately

### ISSUE THREAD

**Issue by lingniao2000** [the4thdoctor/pg_chameleon#47]
hi,
my  environment is  centos 7.3, python 3.5.3.  We have been testing pg_chameleon 2.0.0a3 for a week now. The problem is now
Using pg_chameleon init_replica migrate data to  PG there is no problem, but when I manually update a record in the source mysql, PG will not be applied immediately. Unless I manually execute flush logs or DDL statements in the mysql side to trigger reply.
In addition, there is another problem, that every time I start_replica will create a copy thread in the mysql side, even if I executed stop_replica. In linux using netstat view mysql side, tcp connection shows close_wait state

We also analyzed the python source code, looks like the class mysql_source, read_replica_stream function "for binlogevent in my_stream:" This statment has been waiting, no matter whether the mysql source has a new binlog event

I hope someone can help me solve this, thank you very much

**Comment by the4thdoctor** [comment]
Thanks for the report. Do you have any examples to show me so I can reproduce the issue?
Thanks

**Comment by lingniao2000** [comment]
[default.yml.txt](https://github.com/the4thdoctor/pg_chameleon/files/1538490/default.yml.txt)
let me try

Steps:
chameleon.py create_replica_schema --debug
chameleon.py add_source --source pre --config default   
chameleon.py init_replica --source pre --config default --debug
chameleon.py start_replica --config default --source pre --debug

source mysql:  schema finance_wechat,just a simple test table 
 mysql version:5.6.19-0ubuntu0.14.04.1
dest postgresql: PG 10

Execute start_replica, update a test table such as WE_APPS, t_log_replica_pre_1 table can find a binlog record, but WE_APPS really did not be updated

Thanks

**Comment by the4thdoctor** [comment]
I remember that mysql 5.6.19 had some issues in sending the data. any chance you can upgrade at the latest version 5.6.38 (or even 5.6.33 is good)

**Comment by lingniao2000** [comment]
～ Wow!
resolve it ,the root cause is the mysql version 
thank you very much

**Comment by the4thdoctor** [comment]
Cool. Thanks for feedback.
