### ISSUE TITLE
Can I manually specify the binlog file and location?

### ISSUE THREAD

**Issue by lingniao2000** [the4thdoctor/pg_chameleon#48]
In addition to deploying a standalone cascading replica database, can I restore an instance from a backup, then specify binlog files and locations for incremental synchronization. Finally build a simulation of the slave database synchronization.
FLUSH TABLE WITH READ LOCK This online database is not acceptable

**Comment by the4thdoctor** [comment]
Unfortunately the replica library requires a database connection. The only option available to avoid issues with the live database is to use a cascading replica

**Comment by lingniao2000** [comment]
Okay, I got it

**Comment by the4thdoctor** [comment]
I'll add in the version 2.1 the possibility to run the init replica in a single transaction but this will work only for innodb tables. for the myisam the read lock is the only option to get consistent data

**Comment by lingniao2000** [comment]
cool, all our tables are innodb engine, that does not matter.

When can I see this version? :)

2017-12-08 15:48 GMT+08:00 Federico Campoli <notifications@github.com>:

**Comment by the4thdoctor** [comment]
I haven't started the development yet. I will begin the new cycle when the 2.0 is out. 
Probably by the middle of January 2018 there will be something.

**Comment by lingniao2000** [comment]
Great, it's really cool !

2017-12-12 0:53 GMT+08:00 Federico Campoli <notifications@github.com>:
