### ISSUE TITLE
can I add tables synchronization to PG at any time?

### ISSUE THREAD

**Issue by lingniao2000** [the4thdoctor/pg_chameleon#50]
My MySQL database has a capacity of 1600GB, full table synchronization to PG time is too long, and some data is not needed. I hope to synchronize some of the tables to the PG, but if the requirements change, I can always select some other table synchronization to the PG, how to achieve this requirement?

I tried to add a new source, but the error message:
There is a duplicate destination schema in the schema mappings

What should I do? thanks

**Comment by the4thdoctor** [comment]
hi, it's possible of course. 
if you need to add a new table to the replica just add it to the list of limit_tables: specifying the table in the form SCHEMA.TABLE

then you shall run the command
chameleon.py sync_tables --source <your_source> --tables schema.table1,schema.table2 etc

After the sync is done you can start the replica and the tables will catch up with the consistent status eventually.

Details about the command line reference are here. http://www.pgchameleon.org/documents_v2/usage.html#command-line-reference

If you need to sync an entire schema there is also the command refresh_schema which does the same as sync_tables.

**Comment by lingniao2000** [comment]
Great, I test it and it works, that's  exactly what I needed.

2017-12-11 20:27 GMT+08:00 Federico Campoli <notifications@github.com>:

**Comment by the4thdoctor** [comment]
Happy to help :-)
