### ISSUE TITLE
Source DB downtime and "Connection timed out" errors

### ISSUE THREAD

**Issue by Hoya** [the4thdoctor/pg_chameleon#69]
Hey, I've been using chameleon for a couple of days now and it's working out great. There is one issue that I'd like to check with you.

As I mentioned in one of my previous issues, I'm using AWS RDS and it automatically performs maintenance once a week. During this time it drops all exiting connections for a couple of minutes. 

After looking at the logs it seems like pg_chameleon throws a "Connection timed out" error the read daemon crashes during this brief down time. Is there a way to avoid the read daemon from crashing while continuously retrying to establish a connection?

**Comment by the4thdoctor** [comment]
Hi, I've pushed the change with the commit 9b8e98a which will appear in the upcoming release 2.0.6. However I'm not sure when I'll be able to release it as I'm currently going trough hard time on the personal sphere.
If you want to test it you can just switch to this specific commit and add the parameter `on_error_read: continue` for your source (check config-examople.yml).

Thanks
