### ISSUE TITLE
Feature request: Ability to "skip deletes"

### ISSUE THREAD

**Issue by lukener** [the4thdoctor/pg_chameleon#76]
Hi,

I would like propose a new option to "skip deletes" from the source database.

Goal is to have the target database keeps all the data even when the source application deletes rows, kind of "archive".

Thanks and best regards
René

**Comment by the4thdoctor** [comment]
Hi, thanks for the request.
I'd implement in a flexible way, giving the possibility to enable this skip_deletes per table and per schema.

However the truncate command will still have effect on the excluded tables as it's a different kind of event handled by the system.
Is that ok?

**Comment by lukener** [comment]
Hi,

yes, this would be absolutely sufficient from my perspective.

Best Regards!
