### ISSUE TITLE
Problems with uppercase table and column names?!

### ISSUE THREAD

**Issue by flash4lekker** [the4thdoctor/pg_chameleon#79]
Hey,
I try to sync a mysql of closed source software. The developers have used uppercase table names and column names. I think this might be a problem for pg_chameleon.

2018-06-18 08:08:00 MainProcess INFO: Initialising the replica for source omstest
2018-06-18 08:08:00 MainProcess INFO: deleting all the table references from the replica catalog for source omstest
2018-06-18 08:08:01 MainProcess INFO: Copying the source table PROPERTIES_ID into _omstest_tmp.PROPERTIES_ID
2018-06-18 08:08:02 MainProcess INFO: Could not copy the table PROPERTIES_ID. Excluding it from the replica.
2018-06-18 08:08:02 MainProcess CRITICAL: init replica for source omstest failed

I have found this article: https://stackoverflow.com/questions/43111996/why-postgresql-does-not-like-uppercase-table-names
Maybe table creation isn't done with quotes?
Tables with lowercase name and uppercase column names seem to have the same problem.
greets flash4lekker

**Comment by the4thdoctor** [comment]
Hi, thanks for the report.
As you can see https://github.com/the4thdoctor/pg_chameleon/blob/master/pg_chameleon/lib/pg_lib.py#L2295 the at create table the table name and column names are double quoted. 
Can you please post the PostgreSQL log with the error?

Also, if you can give me the table's definition (in a private paste if you can't share it with public) will help me to understand what's going on.

Anyway, I need to improve this part of the error handling as is not really useful :(

**Comment by flash4lekker** [comment]
Hi, thanks for your reply.
I think the problem is a completely different one :( 
First I have excluded the uppercase tables via "skip_tables", but still no initialization.

Then I found the --debug flag in the command line reference:

`(ml_dwh_sync) pgsync@ws:~$ chameleon init_replica --config omstest --source omstest --debug`
`2018-06-18 15:22:15 MainProcess DEBUG pg_lib.py (616): Changing the autocommit flag to True`
`2018-06-18 15:22:15 MainProcess DEBUG pg_lib.py (616): Changing the autocommit flag to True`
`2018-06-18 15:22:15 MainProcess DEBUG mysql_lib.py (1182): starting init replica for source omstest`
`2018-06-18 15:22:15 MainProcess DEBUG pg_lib.py (616): Changing the autocommit flag to True`
`2018-06-18 15:22:15 MainProcess DEBUG pg_lib.py (2981): Collecting schema mappings for source omstest`
`2018-06-18 15:22:15 MainProcess INFO pg_lib.py (1837): deleting all the table references from the replica catalog for source omstest`
`2018-06-18 15:22:15 MainProcess DEBUG mysql_lib.py (238): Creating the schema _omstest_data_tmp.`
`2018-06-18 15:22:15 MainProcess DEBUG mysql_lib.py (240): Creating the schema omstest_data.`
`2018-06-18 15:22:15 MainProcess DEBUG mysql_lib.py (238): Creating the schema _omstest_tmp.`
`2018-06-18 15:22:15 MainProcess DEBUG mysql_lib.py (240): Creating the schema omstest.`
`2018-06-18 15:22:17 MainProcess INFO mysql_lib.py (644): Copying the source table PROPERTIES_ID into _omstest_tmp.PROPERTIES_ID`
`2018-06-18 15:22:17 MainProcess DEBUG mysql_lib.py (456): estimating rows in omstest.PROPERTIES_ID`
`2018-06-18 15:22:17 MainProcess DEBUG mysql_lib.py (486): The table omstest.PROPERTIES_ID will be copied in 1  estimated slice(s) of 96023 rows`
`2018-06-18 15:22:17 MainProcess DEBUG mysql_lib.py (424): locking the table `omstest`.`PROPERTIES_ID``
`2018-06-18 15:22:17 MainProcess DEBUG mysql_lib.py (426): collecting the master's coordinates for table `omstest`.`PROPERTIES_ID``
`2018-06-18 15:22:17 MainProcess INFO mysql_lib.py (650): Could not copy the table PROPERTIES_ID. Excluding it from the replica.`
`2018-06-18 15:22:17 MainProcess DEBUG mysql_lib.py (251): Dropping the schema _omstest_tmp.`
`2018-06-18 15:22:17 MainProcess DEBUG pg_lib.py (654): Changing the lock timeout for the session to 120s.`
`2018-06-18 15:22:17 MainProcess DEBUG mysql_lib.py (251): Dropping the schema _omstest_data_tmp.`
`2018-06-18 15:22:17 MainProcess DEBUG pg_lib.py (654): Changing the lock timeout for the session to 120s.`
`2018-06-18 15:22:17 MainProcess CRITICAL mysql_lib.py (1216): init replica for source omstest failed`
`Traceback (most recent call last):`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/bin/chameleon", line 5, in <module>`
`    exec(compile(open(__file__).read(), __file__, 'exec'))`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/bin/chameleon.py", line 58, in <module>`
`    getattr(replica, args.command)()`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pg_chameleon/lib/global_lib.py", line 323, in init_replica`
`    self.__init_mysql_replica()`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pg_chameleon/lib/global_lib.py", line 333, in __init_mysql_replica`
`    self.mysql_source.init_replica()`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py", line 1197, in init_replica`
`    self.__copy_tables()`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py", line 646, in __copy_tables`
`    master_status = self.copy_data(schema, table)`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py", line 489, in copy_data`
`    self.lock_table(schema, table)`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py", line 427, in lock_table`
`    self.cursor_buffered.execute(sql_lock)`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute`
`    result = self._query(query)`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query`
`    conn.query(q)`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pymysql/connections.py", line 893, in query`
`    self._affected_rows = self._read_query_result(unbuffered=unbuffered)`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pymysql/connections.py", line 1103, in _read_query_result`
`    result.read()`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pymysql/connections.py", line 1396, in read`
`    first_packet = self.connection._read_packet()`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pymysql/connections.py", line 1059, in _read_packet`
`    packet.check_error()`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pymysql/connections.py", line 384, in check_error`
`    err.raise_mysql_exception(self._data)`
`  File "/home/pgsync/ml_dwh_sync/ml_dwh_sync/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception`
`    raise errorclass(errno, errval)`
`pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WITH READ LOCK' at line 1")`

After that I checked the mysql version :( It is a 5.1.73
pg_chameleon requirements are 5.5+

I think this might be the reason?! :(
greets flash4lekker

**Comment by the4thdoctor** [comment]
AFAIK unfortunately the version 5.1 supports only the statement based replica which is not supported by pg_chameleon.

However, if you just need to migrate the data I warmly recommend pgloader [https://pgloader.io/](https://pgloader.io/) which is highly efficient in moving data with great flexibility.
