### ISSUE TITLE
utf8mb4 to utf8 issue

### ISSUE THREAD

**Issue by Hoya** [the4thdoctor/pg_chameleon#80]
Seems like chameleon is having trouble with converting 4 byte utf8mb4 characters to utf8 on postgres. Below is the warning message:

```
/root/pg_chameleon/venv/lib/python3.5/site-packages/pg_chameleon/lib/mysql_lib.py:572: Warning: (1977, "Cannot convert 'utf8mb4' character 0xF09F8CBF to 'utf8'")
  insert_data =  self.cursor_unbuffered.fetchall()
```

It's not critical at the moment but worth taking a look.

**Comment by the4thdoctor** [comment]
I think this is an issue with the pymysql driver. can you please raise an issue with them?
