### ISSUE TITLE
Over 1.5 h read lag on mysql -> pgsql replica

### ISSUE THREAD

**Issue by apraglowski** [the4thdoctor/pg_chameleon#87]
Hi there, I'm having sad issue with pg_chameleon replicas, while running on staging environment it has about 2 sec read lag which is great, but while running on production in the period where are coworkers are doing stuff (mostly inserts and updates) lag is equall or bigger than 1.5 hour. We are sure that it's not because of mysql server settings. We are using version 2.0.10

Here is a sample of our pg_chameleon config:
skip_tables:
    grant_select_to:
      - pg_user
    lock_timeout: "120s"
    my_server_id: 100
    replica_batch_size: 20000
    replay_max_rows: 10000
    batch_retention: '1 day'
    copy_max_memory: "1200M"
    copy_mode: 'direct' #same problem on file
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: "disabled"
    gtid_enable: No
    type: mysql

Could you advice, what can we change, to make read lag lesser?

**Comment by the4thdoctor** [comment]
thanks. which patch level? I need all the 3 numbers please :)

**Comment by apraglowski** [comment]
Oh sorry -as show version says -  5.6.39-83.1-log

**Comment by the4thdoctor** [comment]
ok, that's shouldn't be the case then. can you please change the logging to debug logs and upload the read log somewhere?

**Comment by apraglowski** [comment]
Sure, just need to switch it back to 2.0.10, because of this bug we switched to 1.80 :)

**Comment by the4thdoctor** [comment]
interesting. so the old 1.8 is not affected by the problem

**Comment by apraglowski** [comment]
I mean, on 1.8 we're starting once per hour 
those two commands: 
chameleon.py add_source --config default  
chameleon.py init_replica --config  default

And ofc on 2.0.10 after init, we are just running start_replica

**Comment by the4thdoctor** [comment]
you can do the init_replica on the 2.0.10 the same way with the bonus of having the process backgrounded :)
anyway, let me know about the logging.

**Comment by apraglowski** [comment]
If it's acceptable for you, I'll send logs at the evening, because of maintenance :) 
As for basing on the init_replica - we're aiming for "live" mysql -> pgsql replica that's we switched onto 2.0.10 version, but those lags makes us go back to 1.80

**Comment by the4thdoctor** [comment]
sure, no worries :)

**Comment by apraglowski** [comment]
Logs from replica (2.0.10) 
https://pastebin.com/pZL93RP1
https://pastebin.com/8rt5cE2x

**Comment by the4thdoctor** [comment]
the data seems collected correctly.
is there any time difference between mysql and postgresql?  or different timezone settings?

**Comment by apraglowski** [comment]
There is no time difference nor timezone stuff. We actually hoped that its the matter of our pg_cham config

**Comment by the4thdoctor** [comment]
I was proposing to run select now(); on both mysql and postgres.
What are the values for both databases?
I think its a bug in the way I display the output as mysql returns the values without timezone, postgresql returns a timestamp with timezone.

**Comment by apraglowski** [comment]
Difference between mysql 2018-09-14 09:00:22 - pgsql 2018-09-14 07:03:22.730254. 
But empirical tests confirm read lag

**Comment by the4thdoctor** [comment]
thanks. In order to reproduce the issue I need to know the operating systems of the percona server, postgresql.
patch level for boths. and the operating system of the machine running pgchameleon with the python version used.

**Comment by apraglowski** [comment]
PostgreSQL 10.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit
======
Debian 8, Python 3.6.3

**Comment by the4thdoctor** [comment]
is percona on the same postgresql's machine?

**Comment by apraglowski** [comment]
yes indeed

**Comment by apraglowski** [comment]
It's okay I can wait :) 
Additional information, there is an read lag despite fact that there is nothing happening on mysql server (no load nor slowqueries etc)

**Comment by lingniao2000** [comment]
Your question may be similar to what I have encountered before.
[Improve the replay function's speed](https://github.com/the4thdoctor/pg_chameleon/issues/59)

**Comment by lingniao2000** [comment]
Wonderful, I will test it again.

**Comment by the4thdoctor** [comment]
did you get any improvement?

**Comment by the4thdoctor** [comment]
I'm assuming it's ok so I'm closing this ticket.
