### ISSUE TITLE
BLOB data are not migrated to bytea as expected

### ISSUE THREAD

**Issue by gboscarino** [the4thdoctor/pg_chameleon#92]
I am migrating a database from MySQL 5.6 to PostgreSQL 10.3. By comparing the content of the corresponding columns (mediumblob to bytea) through the hex function, it seems that the blob data are not replicated as expected; the hex values of the columns in the target table are different from the content of the source columns.

- The source DB has character set utf8 and default_collation utf8_bin.
- chameleon 2.0.10 
- I am using the default settings in the default.yml file.

Thank you,

Gaspare

**Comment by the4thdoctor** [comment]
hi, do you have an example data I can test?
thanks

**Comment by gboscarino** [comment]
Hello,

Please find attached an example of a MySQL table containing BLOB data. The actual binary data are the attached jpg files . The following is the content of the configuration file:

==================================================
---
#global settings
pid_dir: '~/.pg_chameleon/pid/'
log_dir: '~/.pg_chameleon/logs/'
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ''
rollbar_env: ''

# type_override allows the user to override the default type conversion into a different one. 
type_override:
  "tinyint(1)":
    override_to: boolean
    override_tables:
      - "*"

  
      

#postgres  destination connection
pg_conn:
  host: "pg02"
  port: "5432"    
  user: "prime"
  password: "pwd123"
  database: "qa_prime_core"
  charset: "utf8"
    
sources:
  mysql:
    db_conn:
      host: "pg01"
      port: "3306"
      user: "repl"
      password: "pwd123"
      charset: 'utf8'
      connect_timeout: 10
    schema_mappings:
      qa_prime_core: prime
    limit_tables:
#      - delphis_mediterranea.foo
    skip_tables:
#      - delphis_mediterranea.bar
    grant_select_to:
      - prime
    lock_timeout: "120s"
    my_server_id: 100
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: '1 day'
    copy_max_memory: "300M"
    copy_mode: 'direct'  
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: "disabled"
    gtid_enable: No
    type: mysql
    skip_events:
      insert:
#        - delphis_mediterranea.foo #skips inserts on the table delphis_mediterranea.foo
      delete:
#        - delphis_mediterranea #skips deletes on schema delphis_mediterranea
      update:
=======================================================


It seems that there are some problems regarding the decoding of the BASE64 binary data before the insert into the target BYTEA columns. 
[default.txt](https://github.com/the4thdoctor/pg_chameleon/files/2819747/default.txt)



Thank you,

Gaspare

[bin_files_01.zip](https://github.com/the4thdoctor/pg_chameleon/files/2819714/bin_files_01.zip)
![picture-02](https://user-images.githubusercontent.com/2336529/52097393-c9e7d980-257f-11e9-93a8-405907dabff7.jpg)
![picture-01](https://user-images.githubusercontent.com/2336529/52097402-cd7b6080-257f-11e9-9f51-5cff4b2ca980.jpg)

**Comment by the4thdoctor** [comment]
Sorry for the long wait. I've assessed the issue. It seems the replay function is converting wrongly the bytea to strings. I'll work on a fix but it will take some extra time.
At init_replica time the data seems ok to me though.

**Comment by the4thdoctor** [comment]
I've picked up the issue again, and this time I get the images in postgresql replicated. 
this happens after the init replica and during the replica process.
Are you still experiencing the problem?

**Comment by the4thdoctor** [comment]
it seems it's not a bug after all. With postgresql you can extract the binary data with the command
`SET bytea_output='escape';`
`SELECT decode(<FIELD>::text,'hex') from <TABLE>;`
