### ISSUE TITLE
SOLVED - Unable to begin replica with MySQL 5.7 and Postgres 10

### ISSUE THREAD

**Issue by acpmasquerade** [the4thdoctor/pg_chameleon#94]
python version 3.6.7

$ ...site-packages/pg_chameleon-2.0.10-py3.6.egg/pg_chameleon/lib/pg_lib.py", line 2171, in check_schema_mappings
**psycopg2.DataError: cannot deconstruct an array as an object**

**Comment by acpmasquerade** [comment]
Upon trying with Postgres 9.6, I received the same error.
So, I thought of checking the configuration file once again. After removing the lines
- skip_tables
- limit_tables
- schema_mappings
Then, I received another error saying `KeyError: 'schema_mappings'`

To fix that, I kept empty dictionary values for these three keys
- skip_tables: {}
- limit_tables: {}
- schema_mappings: {}

And the  command succeeded.

Suggestion: If the values were mandatory, it would be very helpful to parse the config file, and dump all key errors or any other possible errors before execution.

Thanks.

**Comment by the4thdoctor** [comment]
that's weird. I need to check if the latest pyaml library introduced some regression as the empty values have worked fine.
Thanks for the report.

**Comment by the4thdoctor** [comment]
You can't have the `schema_mappings:` empty. Is compulsory to have a mapping between mysql and postgresql otherwise you'll get unpredictable results. 
I will add a check for the key to have at least one mapping when bootstrapping the process.

**Comment by acpmasquerade** [comment]
Adding the suggested checks I had listed out

- at-least one schema mapping is available
- verifies both the source and destination connections (on init or by providing a subcommand to do that)
- required keys like `skip_tables`, `limit_tables` are present if mandatory, or if not present, then would rather regard as the setting wasn't required

Thanks again
