### ISSUE TITLE
default configs aren't even valid yaml?

### ISSUE THREAD

**Issue by robclancy** [the4thdoctor/pg_chameleon#95]
https://github.com/the4thdoctor/pg_chameleon/commit/30fc790edba6c00d7460d831993cdbecd2aa827b#diff-cfd5078f9f74b028514ffcc5cb33cf7fR58

**Comment by the4thdoctor** [comment]
can you elaborate please?

**Comment by robclancy** [comment]
Just look at it? The indentation is all wrong? https://github.com/the4thdoctor/pg_chameleon/blob/master/configuration/config-example.yml#L69

**Comment by the4thdoctor** [comment]
Mmmm 2 spaces. I don't get it. I fixed the extra spaces long time ago.

**Comment by robclancy** [comment]
There is no space before `db_conn:`, there is extra indentation on everything after `connect_timeout: 10`

Just look at it holy shit. Even after fixing this it didn't work and I went with something else, thought I would make a simple bug report that shows SO clearly what the issue is and you seem to not even look. You can see the issue in both links.

Just going to close this, you can fix it when someone else tries using this for the first time and you actually look at the file.

**Comment by rebtoor** [comment]
Hi, i just submitted a [PR](https://github.com/the4thdoctor/pg_chameleon/pull/97) to fix these errors. There are no validation errors now (tested with yamllint).
